# Generated by Django 5.2.7 on 2025-10-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0001_initial'),
    ]

    operations = [
        # --- Modèle de révisions ---
        migrations.CreateModel(
            name='EventoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.IntegerField()),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # --- Renommer la contrainte UNIQUE du slot calendrier ---
        # (on retire l'ancienne pour éviter le doublon, puis on ajoute la nouvelle)
        migrations.RemoveConstraint(
            model_name='calendarioslot',
            name='unique_data_location',
        ),
        migrations.AddConstraint(
            model_name='calendarioslot',
            constraint=models.UniqueConstraint(
                fields=('data', 'location_index'),
                name='uniq_slot_date_loc'
            ),
        ),

        # --- Colonnes manquantes ---
        migrations.AddField(
            model_name='materiale',
            name='scorta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rigaevento',
            name='copertura_giorni',
            field=models.IntegerField(default=1),
        ),

        # --- Index (non-unique) pour accélérer les requêtes sur date+location ---
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(
                fields=['data_evento', 'location_index'],
                name='eventi_even_data_loc_idx'
            ),
        ),

        # ⚠️ PAS de UniqueConstraint sur Evento(data_evento, location_index) ici.
        #    L'unicité fonctionnelle est assurée par CalendarioSlot + validation serializer.

        # --- FK + unique_together pour les révisions ---
        migrations.AddField(
            model_name='eventorevision',
            name='evento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='revisions',
                to='eventi.evento'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='eventorevision',
            unique_together={('evento', 'ref')},
        ),
    ]
