# Generated by Django 5.2.7 on 2025-10-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0002_eventorevision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorevision',
            name='updated_at',
        ),
    ]
