# Generated by Django 5.2.7 on 2025-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0003_remove_eventorevision_updated_at'),
    ]

    operations = [
        # no-op: on n'ajoute plus d'unicité sur Evento en 0002,
        # donc rien à retirer ici.
    ]
