# Generated by Django 5.2.7 on 2025-10-24

from django.db import migrations, models
from decimal import Decimal

class Migration(migrations.Migration):

    # ⚠ Ajuste la dépendance pour qu'elle pointe vers TA dernière migration existante
    dependencies = [
        ('eventi', '0004_remove_evento_uniq_evento_date_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acconto_importo',
            field=models.DecimalField(default=Decimal("0.00"), max_digits=10, decimal_places=2),
        ),
        migrations.AddField(
            model_name='evento',
            name='acconto_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
