# Generated by Django 5.2.7 on 2025-10-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0005_add_evento_acconto_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventolog',
            name='evento',
        ),
        migrations.RemoveConstraint(
            model_name='calendarioslot',
            name='uniq_slot_date_loc',
        ),
        migrations.RenameIndex(
            model_name='evento',
            new_name='eventi_even_data_ev_454aaf_idx',
            old_name='eventi_even_data_loc_idx',
        ),
        migrations.DeleteModel(
            name='EventoLog',
        ),
    ]
