# Generated by Django 5.2.7 on 2025-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0006_remove_eventolog_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiale',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
