# Generated by Django 5.2.7 on 2025-10-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0007_materiale_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegolaSuggerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_categoria', models.CharField(blank=True, max_length=120)),
                ('trigger_sottocategoria', models.CharField(blank=True, max_length=120)),
                ('suggest_categoria', models.CharField(blank=True, max_length=120)),
                ('suggest_sottocategoria', models.CharField(blank=True, max_length=120)),
                ('qty_default', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='materiale',
            name='is_default_service',
            field=models.BooleanField(default=False, help_text='Se attivo: il materiale viene proposto come servizio predefinito (Tecnico/Messo).'),
        ),
        migrations.CreateModel(
            name='MaterialeSuggerito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_default', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('suggested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggerito_da', to='eventi.materiale')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggerimenti', to='eventi.materiale')),
            ],
            options={
                'unique_together': {('trigger', 'suggested')},
            },
        ),
    ]
