# Generated by Django 5.2.7 on 2025-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0008_regolasuggerimento_materiale_is_default_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acconto_state',
            field=models.CharField(choices=[('none', 'None'), ('to_send', 'Da inviare'), ('sent', 'Inviato'), ('paid', 'Pagato')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='evento',
            name='offerta_stato',
            field=models.CharField(choices=[('da_eseguire', 'DA ESEGUIRE'), ('inviato', 'INVIATO'), ('annullato', 'ANNULLATO')], default='da_eseguire', max_length=16),
        ),
        migrations.AddField(
            model_name='evento',
            name='saldo_state',
            field=models.CharField(choices=[('none', 'None'), ('to_send', 'Da inviare'), ('sent', 'Inviato'), ('paid', 'Pagato')], default='to_send', max_length=16),
        ),
    ]
