# Generated by Django 5.2.7 on 2025-10-30 19:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0009_evento_acconto_state_evento_offerta_stato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='acconto_importo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='evento',
            name='acconto_state',
            field=models.CharField(choices=[('none', 'none'), ('to_send', 'to_send'), ('sent', 'sent'), ('paid', 'paid')], default='none', max_length=8),
        ),
        migrations.AlterField(
            model_name='evento',
            name='offerta_stato',
            field=models.CharField(choices=[('da_eseguire', 'DA ESEGUIRE'), ('inviato', 'INVIATO'), ('annullato', 'ANNULLATO')], default='da_eseguire', max_length=12),
        ),
        migrations.AlterField(
            model_name='evento',
            name='saldo_state',
            field=models.CharField(choices=[('none', 'none'), ('to_send', 'to_send'), ('sent', 'sent'), ('paid', 'paid')], default='to_send', max_length=8),
        ),
    ]
