# Generated by Django 5.2.7 on 2025-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0010_alter_evento_acconto_importo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
