# Generated by Django 5.2.7 on 2025-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0012_mezzo_tecnico_luogo_distanza_km_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorevision',
            options={'ordering': ('created_at', 'ref')},
        ),
        migrations.AddField(
            model_name='eventorevision',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
