# Generated by Django 5.2.7 on 2025-11-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0013_alter_eventorevision_options_eventorevision_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='materiale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materiale',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='materiale',
            name='unit_label',
            field=models.CharField(choices=[('pz', 'pz'), ('h', 'h'), ('km', 'km')], default='pz', help_text='Unité de tarification: pz=pièce, h=heure (tecnico), km=km (mezzo)', max_length=8),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='is_default_service',
            field=models.BooleanField(default=False, help_text='Si actif, proposé comme service par défaut (Tecnico/Messo).'),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='is_messo',
            field=models.BooleanField(default=False, help_text='Article de type mezzo/transport (facturé au km)'),
        ),
        migrations.AlterField(
            model_name='materiale',
            name='is_tecnico',
            field=models.BooleanField(default=False, help_text="Article de type technicien (facturé à l'heure)"),
        ),
        migrations.CreateModel(
            name='Sottocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventi.categoria')),
            ],
        ),
    ]
