# Generated by Django 5.2.7 on 2025-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0014_categoria_remove_materiale_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorevision',
            options={'ordering': ['created_at', 'ref']},
        ),
        migrations.AlterField(
            model_name='evento',
            name='versione',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventorevision',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventorevision',
            name='ref',
            field=models.PositiveIntegerField(),
        ),
    ]
