# Generated by Django 5.2.7 on 2025-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0015_alter_eventorevision_options_alter_evento_versione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='distanza_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='km usati per logistica', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='costo_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='€/km (opz., rimborso viaggio)', max_digits=7),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='tariffa_oraria',
            field=models.DecimalField(decimal_places=2, default=0, help_text='€/h', max_digits=8),
        ),
        migrations.AlterField(
            model_name='mezzo',
            name='costo_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='€/km', max_digits=7),
        ),
    ]
