# Generated by Django 5.2.7 on 2025-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0016_evento_distanza_km_tecnico_costo_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luogo',
            name='cap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='luogo',
            name='citta',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='luogo',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
