# Generated by Django 5.2.7 on 2025-11-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0017_luogo_cap_luogo_citta_luogo_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_evento_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento_da',
            field=models.DateField(blank=True, null=True),
        ),
    ]
